[local]
localhost

[mongodb]
mongodb.devpreactice.online

[redis]
redis.devpreactice.online

[mysql]
mysql.devpreactice.online

[rabbitmq]
rabbitmq.devpreactice.online

[catalogue]
catalogue.devpreactice.online